# Generated by Django 4.0.3 on 2022-03-17 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField()),
                ('created_on', models.DateTimeField()),
                ('updated_on', models.DateTimeField()),
                ('is_approved', models.BooleanField(default=True)),
                ('approved_by', models.CharField(max_length=100)),
                ('food_group', models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior'), ('GR', 'Graduate')], default='FR', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Kid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kid_name', models.CharField(max_length=100)),
                ('kid_age', models.IntegerField(max_length=100)),
                ('parent_phone_number', models.CharField(max_length=12)),
                ('parent_email_address', models.EmailField(max_length=100)),
            ],
        ),
    ]
