# Generated by Django 4.0.3 on 2022-03-17 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forfun', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='food_group',
            field=models.CharField(choices=[('fruit', 'Fruit'), ('veg', 'Veg'), ('grain', 'Grain'), ('protein', 'Protein'), ('dairy', 'Dairy'), ('confectionery', 'Confectionery'), ('unknown', 'Unknown')], default='unknown', max_length=20),
        ),
    ]
