# Generated by Django 4.0.3 on 2022-03-19 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forfun', '0003_alter_kid_kid_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='kid',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='forfun.kid'),
            preserve_default=False,
        ),
    ]
